### ISSUE TITLE
how to decode bak to sql query format

### ISSUE THREAD

**Issue by antoinekondoh** [vmkernel/expense-iq#1]
Hello, I would kindly like some help in the process to decode my expense iq .bak to sql querry so I can use your tool.

**Comment by vmkernel** [comment]
Hi, what kind of problem do you have with deciding?

**Comment by antoinekondoh** [comment]
I only know basic programming in python so my challenge was with powershell
scripts and how to run them. However these are the steps I took to
successfully get the bug fixed.

1.I edited the decrypt.py shared by raphaelm to create an sql copy of the
database identifying the indexes of the lines with the 's issue.

2. I opened this .bak file with Notepad++. I showed me all the lines
representative of the tables from my backup but in Hexadicmal format.

3. I run each of the functions in the expense-iq-backup.ps1 directly in the
powershell prompt. thereafter I edited and run the lines of code in the
fault-line-fix.ps1 to correct the lines with the 's identified from step 1.

4. for each of these new Hex lines outputted from your fault-line-fix.ps1,
I copied and pasted them in the original .bak file opened in Notepad++.

5. Finally I put the in the expense-iq folder on my new phone and voila,
the backup restored everything as expected.

I am very grateful for your skill and that of raphaelm in coding this
solution.

NB: Please in your script there is a comment under the
encode-expenseiqbackup function that says

#TODO: Implementation

I would kindly like to know what that meant. Thank you.

With Regards,
Antoine

**Comment by vmkernel** [comment]
So, if I've understood correctly, you've managed to fix the issue(s) in your backup?
In this case - congratulations! ))


> I would kindly like to know what that meant.
> #TODO: Implementation

It's a comment for myself to actually write logic of this function, cause for now it does literally nothing. 
Originally I wanted it to automatically convert a whole sql file back to a file in obfuscated backup format of Expense IQ. It ment to be an "opposite" function of Decode-ExpenseIqBackup. But since I'd managed to fix my backup file in the same way you did, I decided to do it later. That was two and a half years ago :))

**Comment by antoinekondoh** [comment]
Well after you've solved the problem that got you coding in the first
place, it's understandable that you've not gone back to it. Thanks again
for the assistance

**Comment by vmkernel** [comment]
(Finally) implemented in [fix_and_update](https://github.com/vmkernel/expense-iq/blob/fix_and_update/) branch.
Will be merged in the **master** soon.
